version: 2.1

orbs:
  clojure: lambdaisland/clojure@dev:first

commands:
  checkout_and_run:
    parameters:
      target:
        type: string
      clojure_version:
        type: string
    steps:
    - checkout
    - clojure/with_cache:
        cache_version: << parameters.clojure_version >>
        steps:
        - run: make << parameters.target >>

jobs:
  openjdk8:
    executor: clojure/openjdk8
    parameters:
      target:
        type: string
      clojure_version:
        type: string
    environment: {CLOJURE_VERSION: << parameters.clojure_version >>}
    steps:
    - checkout_and_run:
        target: << parameters.target >>
        clojure_version: <<parameters.clojure_version>>

workflows:
  version: 2
  cider_tests:
    jobs:
    - openjdk8:
        clojure_version: "1.8"
        target: test-clj
    - openjdk8:
        clojure_version: "1.9"
        target: test-clj
