version: 2.1

orbs:
  clojure: lambdaisland/clojure@dev:first

commands:
  checkout_and_run:
    parameters:
      target:
        type: string
        default: test-clj
    steps:
      - checkout
      - clojure/with_cache:
          cache_version: {{ .Environment.CLOJURE_VERSION }}
          steps:
            - run: make << parameters.target >>

jobs:
  CLJ-Java8-Clojure18:
    executor: clojure/openjdk8
    environment: {CLOJURE_VERSION: 1.8}
    steps: [checkout_and_run]

workflows:
  version: 2
  cider_tests:
    jobs:
      - CLJ-Java8-Clojure18
